name: Build APK with Buildozer
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev tk-dev libgdbm-compat-dev libreoffice-dev libmpdec-dev
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Build with Buildozer
      run: |
        mkdir -p bin
        export FORCE_BUILDOZER_ROOT=1
        
        # أمر ذكي لتجهيز مسار رخص الأندرويد يدوياً داخل بيئة هوم السيرفر
        mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
        echo -e "\n241a150e7190064bec0f17c9429509a340114597\n1ee7733563f7438288aeb4e2ed4dca1c23132bc3\n8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb74bf62295022c3465d\n2f4c55d261174122d9b35b2111d6d5ef104a080b\nc10a5666b52111b113a113a113a113a113a113a1" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        
        # إجبار الأداة على تحميل أدوات بناء مستقرة وقديمة متوافقة مع السيرفر بدلاً من إصدار 37 التجريبي
        sed -i 's/#android.build_tools_version =/android.build_tools_version = 33.0.0/g' buildozer.spec
        
        buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Azkar-App-APK
        path: bin/*.apk



